name: Auto Versioning with Keywords
on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for existing tags
      id: checktag
      run: echo "::set-output name=exists::$(git tag | wc -l)"

    - name: Get latest tag
      id: latesttag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0 || echo 'v0.0.0')"

    - name: Get latest commit message
      id: commitmsg
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"

    - name: Increment version based on keywords
      id: newversion
      run: |
        latest_tag=${{ steps.latesttag.outputs.tag }}
        commit_message=${{ steps.commitmsg.outputs.message }}
        IFS='.' read -ra VERSION_PARTS <<< "${latest_tag#v}"
        major=${VERSION_PARTS[0]}
        minor=${VERSION_PARTS[1]}
        patch=${VERSION_PARTS[2]}

        if [[ $commit_message == *"EXPANSION"* ]]; then
          major=$((major + 1))
          minor=0
          patch=0
        elif [[ $commit_message == *"FEATURE"* ]]; then
          minor=$((minor + 1))
          patch=0
        else
          patch=$((patch + 1))
        fi

        new_version="v$major.$minor.$patch"
        echo "::set-output name=version::$new_version"

    - name: Create new tag
      run: git tag ${{ steps.newversion.outputs.version }}

    - name: Push tags
      run: git push origin --tags
