name: Build and Release

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0  # Fetches all history for all branches and tags
        lfs: true

    - name: Get commit message
      id: get_commit_message
      run: |
        echo "::set-output name=message::$(git log -1 --pretty=format:"%s%n%n%b" ${{ github.ref }})"

    - name: Install GitHub CLI
      run: |
        choco install gh -y

    - name: Authenticate with GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Release and Upload Asset
      run: |
        gh release create ${{ github.ref_name }} ./Releases/ZombieSurvivalRPG_v${{ github.ref_name }}.7z -t "Release ${{ github.ref_name }}" -n "${{ steps.get_commit_message.outputs.message }}"

    - name: Log error
      if: failure()
      run: echo "An error occurred in the previous steps"
