name: Build and Release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract version from commit message
      run: echo "VERSION=$(git log -1 --pretty=%B | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')" >> $GITHUB_ENV

    - name: Generate changelog
      run: git log --pretty=format:"%s" > changelog.txt

    - name: Build Game
      env:
        VERSION: ${{ env.VERSION }}
      run: .\BuildGame.bat

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body_path: changelog.txt
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Releases/ZombieSurvivalRPG_${{ env.VERSION }}.7z
        asset_name: ZombieSurvivalRPG_${{ env.VERSION }}.7z
        asset_content_type: application/x-7z-compressed

    - name: Delete .7z File
      run: rm ./Releases/ZombieSurvivalRPG_${{ env.VERSION }}.7z
