name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - 'Releases/*'
      - 'Assets/version.txt'  # Trigger workflow if version.txt changes

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0  # Fetches all history for all branches and tags
        lfs: true  # Fetch Git LFS objects

    # Check if version has changed
    - name: Check if version has changed
      id: check_version
      run: |
        git diff --name-only HEAD^ HEAD | grep 'Assets/version.txt'
        if [ $? -eq 0 ]; then
          echo "Version has changed, proceeding with build."
          echo "VERSION_CHANGED=true" >> $GITHUB_ENV
        else
          echo "Version has not changed, skipping build."
          echo "VERSION_CHANGED=false" >> $GITHUB_ENV
        fi

    # Conditionally proceed with the rest of the steps
    - name: List contents of Releases directory
      if: env.VERSION_CHANGED == 'true'
      run: ls -l ./Releases

    # Debugging: Print environment variables
    - name: Print environment variables
      if: env.VERSION_CHANGED == 'true'
      run: env

    # Read version from file and set environment variable
    - name: Read version from file
      if: env.VERSION_CHANGED == 'true'
      run: |
        $version = Get-Content Assets/version.txt  # Replace with the actual path
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh

    # Check if VERSION is set
    - name: Check if VERSION is set
      if: env.VERSION_CHANGED == 'true'
      run: |
        if ($null -eq $env:VERSION -or $env:VERSION -eq "") {
          Write-Host "Error: VERSION is not set. Cannot create a GitHub release without a tag name."
          exit 1
        }
      shell: pwsh

    # Delete existing tag
    - name: Delete existing tag
      if: env.VERSION_CHANGED == 'true'
      run: |
        git tag -d ${{ env.VERSION }} || true
        git push origin :refs/tags/${{ env.VERSION }} || true

    # Create and push new tag
    - name: Create and push new tag
      if: env.VERSION_CHANGED == 'true'
      run: |
        git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
        git push origin ${{ env.VERSION }}

    # Create GitHub Release
    - name: Create GitHub Release
      if: env.VERSION != ''
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: 'Description of the release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Run Unity Tests
    - name: Run Unity Tests
      if: env.VERSION_CHANGED == 'true'
      run: |
        # Add your Unity test commands here

    # Log error
    - name: Log error
      if: failure()
      run: echo "An error occurred in the previous steps"
