name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0  # Fetches all history for all branches and tags
        lfs: true

    - name: Extract version number from .7z file
      run: |
        VERSION=$(ls ./Releases/*.7z | grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+')
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Delete existing tag
      run: |
        git tag -d ${{ env.VERSION }} || true
        git push origin :refs/tags/${{ env.VERSION }} || true

    - name: Create and push new tag
      run: |
        git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
        git push origin ${{ env.VERSION }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: 'Description of the release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Log error
      if: failure()
      run: echo "An error occurred in the previous steps"
