name: Build and Release

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Generate changelog
      run: git log --pretty=format:"%s" > changelog.txt

    - name: Build Game
      run: .\BuildGame.bat ${{ github.ref_name }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body_path: changelog.txt
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./Releases/ZombieSurvivalRPG_v${{ github.ref_name }}.7z
        asset_name: ZombieSurvivalRPG_v${{ github.ref_name }}.7z
        asset_content_type: application/x-7z-compressed
