name: Build and Release

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0  # Fetches all history for all branches and tags

    # Generates a changelog based on your Git history
    - name: Generate changelog
      run: git log --pretty=format:"%s" > changelog.txt

    # Creates a new GitHub release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}  # Uses the tag name for the release
        release_name: Release ${{ github.ref_name }}  # Sets the release name
        body_path: changelog.txt  # Sets the body of the release to the changelog
        draft: false  # The release is not a draft
        prerelease: false  # The release is not a pre-release
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # GitHub token for authentication

    # Uploads the built game as a release asset
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  # Gets the upload URL from the create_release step
        asset_path: C:/Users/nyxar/Zombie Survival RPG/Releases/ZombieSurvivalRPG_v${{ github.ref_name }}.7z  # Path to the asset to upload (use forward slashes)
        asset_name: ZombieSurvivalRPG_v${{ github.ref_name }}.7z  # Name of the asset
        asset_content_type: application/x-7z-compressed  # Content type of the asset
